language: android
sudo: true
env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=28.0.3
  - ADB_INSTALL_TIMEOUT=26
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$ANDROID_API
before_install:
- openssl aes-256-cbc -K $encrypted_9de7bdd93c7b_key -iv $encrypted_9de7bdd93c7b_iv
  -in keydata.tar.enc -out keydata.tar -d
- tar xvf keydata.tar
- chmod +x ./gradlew
- gem install fir-cli
install:
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "cmake;3.6.4111459"
- echo y | sdkmanager "lldb;3.1"
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
